# 실행 순서
#   FROM - WHERE - GROUP BY - HAVING - SELECT - ORDER BY - LIMIT
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk','Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID