# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
# , COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS
# , ROUND(COUNT(DISTINCT U.USER_ID) / 
#         (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
# FROM USER_INFO U
# JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
# WHERE YEAR(U.JOINED) = 2021
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)#, U.USER_ID;


# SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.USER_ID
# FROM ONLINE_SALE S
# JOIN USER_INFO U ON S.USER_ID = U.USER_ID AND YEAR(JOINED) = 2021


# # 2021년에 가입한 전체 회원 수
# SELECT COUNT(USER_ID) FROM USER_INFO
# WHERE YEAR(JOINED) = 2021






# mysql 정답
SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS,
	ROUND((COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.USER_ID
    FROM ONLINE_SALE S
    JOIN USER_INFO U ON S.USER_ID = U.USER_ID AND YEAR(JOINED) = 2021
) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH