# FIRST_HALF PK FLAVOR
# ICECREAM_INFO PK/FK FLAVOR
SELECT fh.FLAVOR
FROM FIRST_HALF fh
LEFT JOIN ICECREAM_INFO ii
ON fh.FLAVOR = ii.FLAVOR
WHERE fh.TOTAL_ORDER > 3000
AND ii.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY fh.TOTAL_ORDER DESC
;
         
# SELECT a.FLAVOR 
# FROM FIRST_HALF AS a 
# LEFT JOIN ICECREAM_INFO AS b 
# ON a.FLAVOR = b.FLAVOR
# WHERE a.TOTAL_ORDER > 3000 AND b.INGREDIENT_TYPE LIKE 'fruit_based'
# ORDER BY a.TOTAL_ORDER DESC;