SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) AS TMP
ON TMP.FLAVOR = FH.FLAVOR
ORDER BY FH.TOTAL_ORDER + TMP.TOTAL_ORDER DESC
LIMIT 3







# SELECT J.FLAVOR
# FROM FIRST_HALF F
# RIGHT JOIN JULY J ON F.SHIPMENT_ID = J.SHIPMENT_ID
# GROUP BY J.FLAVOR
# ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
# LIMIT 3

# SELECT F.FLAVOR FROM FIRST_HALF F
# JOIN (SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS TOTAL_ORDER FROM JULY J GROUP BY J.FLAVOR) AS TMP
# ON F.FLAVOR = TMP.FLAVOR
# GROUP BY F.FLAVOR
# ORDER BY F.TOTAL_ORDER + TMP.TOTAL_ORDER DESC
# LIMIT 3