SELECT USER_ID, NICKNAME
, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES



# SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD A
# JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
# WHERE A.STATUS = 'DONE'
# GROUP BY B.USER_ID
# HAVING TOTAL_SALES >= 700000
# ORDER BY TOTAL_SALES