SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM AUTHOR A
JOIN BOOK B ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01' # 2022년 1월
GROUP BY A.AUTHOR_ID, B.CATEGORY # 저자 별, 카테고리 별
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC # 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 


